#############################################################################
# Makefile for building: CPPStockBackend
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  CPPStockBackend.pro
# Template: subdirs
# Command: C:\Qt\5.6\msvc2015_64\bin\qmake.exe -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile CPPStockBackend.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.6\msvc2015_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-BackEndApplication \
		sub-JsonWriter \
		sub-QTHttpGet \
		sub-QtYahooFinanceLib \
		sub-MiscHelpers \
		sub-qhttpserver \
		sub-QtWebServiceApi


sub-BackEndApplication-qmake_all: sub-QtYahooFinanceLib-qmake_all sub-QtWebServiceApi-qmake_all FORCE
	@if not exist BackEndApplication\ mkdir BackEndApplication\ & if not exist BackEndApplication\ exit 1
	cd BackEndApplication\ && $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\BackEndApplication\BackEndApplication.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BackEndApplication\ && $(MAKE) -f Makefile qmake_all
sub-BackEndApplication: sub-QtYahooFinanceLib \
		sub-QtWebServiceApi FORCE
	@if not exist BackEndApplication\ mkdir BackEndApplication\ & if not exist BackEndApplication\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BackEndApplication\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\BackEndApplication\BackEndApplication.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-BackEndApplication-make_first: sub-QtYahooFinanceLib-make_first sub-QtWebServiceApi-make_first FORCE
	@if not exist BackEndApplication\ mkdir BackEndApplication\ & if not exist BackEndApplication\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BackEndApplication\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\BackEndApplication\BackEndApplication.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-BackEndApplication-all: sub-QtYahooFinanceLib-all sub-QtWebServiceApi-all FORCE
	@if not exist BackEndApplication\ mkdir BackEndApplication\ & if not exist BackEndApplication\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BackEndApplication\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\BackEndApplication\BackEndApplication.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-BackEndApplication-clean: sub-QtYahooFinanceLib-clean sub-QtWebServiceApi-clean FORCE
	@if not exist BackEndApplication\ mkdir BackEndApplication\ & if not exist BackEndApplication\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BackEndApplication\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\BackEndApplication\BackEndApplication.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-BackEndApplication-distclean: sub-QtYahooFinanceLib-distclean sub-QtWebServiceApi-distclean FORCE
	@if not exist BackEndApplication\ mkdir BackEndApplication\ & if not exist BackEndApplication\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BackEndApplication\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\BackEndApplication\BackEndApplication.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-BackEndApplication-install_subtargets: sub-QtYahooFinanceLib-install_subtargets sub-QtWebServiceApi-install_subtargets FORCE
	@if not exist BackEndApplication\ mkdir BackEndApplication\ & if not exist BackEndApplication\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BackEndApplication\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\BackEndApplication\BackEndApplication.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-BackEndApplication-uninstall_subtargets: sub-QtYahooFinanceLib-uninstall_subtargets sub-QtWebServiceApi-uninstall_subtargets FORCE
	@if not exist BackEndApplication\ mkdir BackEndApplication\ & if not exist BackEndApplication\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BackEndApplication\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\BackEndApplication\BackEndApplication.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-JsonWriter-qmake_all:  FORCE
	@if not exist JsonWriter\ mkdir JsonWriter\ & if not exist JsonWriter\ exit 1
	cd JsonWriter\ && $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\JsonWriter\JsonWriter.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd JsonWriter\ && $(MAKE) -f Makefile qmake_all
sub-JsonWriter: FORCE
	@if not exist JsonWriter\ mkdir JsonWriter\ & if not exist JsonWriter\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd JsonWriter\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\JsonWriter\JsonWriter.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-JsonWriter-make_first: FORCE
	@if not exist JsonWriter\ mkdir JsonWriter\ & if not exist JsonWriter\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd JsonWriter\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\JsonWriter\JsonWriter.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-JsonWriter-all: FORCE
	@if not exist JsonWriter\ mkdir JsonWriter\ & if not exist JsonWriter\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd JsonWriter\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\JsonWriter\JsonWriter.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-JsonWriter-clean: FORCE
	@if not exist JsonWriter\ mkdir JsonWriter\ & if not exist JsonWriter\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd JsonWriter\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\JsonWriter\JsonWriter.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-JsonWriter-distclean: FORCE
	@if not exist JsonWriter\ mkdir JsonWriter\ & if not exist JsonWriter\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd JsonWriter\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\JsonWriter\JsonWriter.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-JsonWriter-install_subtargets: FORCE
	@if not exist JsonWriter\ mkdir JsonWriter\ & if not exist JsonWriter\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd JsonWriter\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\JsonWriter\JsonWriter.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-JsonWriter-uninstall_subtargets: FORCE
	@if not exist JsonWriter\ mkdir JsonWriter\ & if not exist JsonWriter\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd JsonWriter\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\JsonWriter\JsonWriter.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-QTHttpGet-qmake_all:  FORCE
	@if not exist QTHttpGet\ mkdir QTHttpGet\ & if not exist QTHttpGet\ exit 1
	cd QTHttpGet\ && $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QTHttpGet\QTHttpGet.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QTHttpGet\ && $(MAKE) -f Makefile qmake_all
sub-QTHttpGet: FORCE
	@if not exist QTHttpGet\ mkdir QTHttpGet\ & if not exist QTHttpGet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QTHttpGet\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QTHttpGet\QTHttpGet.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-QTHttpGet-make_first: FORCE
	@if not exist QTHttpGet\ mkdir QTHttpGet\ & if not exist QTHttpGet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QTHttpGet\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QTHttpGet\QTHttpGet.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-QTHttpGet-all: FORCE
	@if not exist QTHttpGet\ mkdir QTHttpGet\ & if not exist QTHttpGet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QTHttpGet\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QTHttpGet\QTHttpGet.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-QTHttpGet-clean: FORCE
	@if not exist QTHttpGet\ mkdir QTHttpGet\ & if not exist QTHttpGet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QTHttpGet\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QTHttpGet\QTHttpGet.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-QTHttpGet-distclean: FORCE
	@if not exist QTHttpGet\ mkdir QTHttpGet\ & if not exist QTHttpGet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QTHttpGet\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QTHttpGet\QTHttpGet.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-QTHttpGet-install_subtargets: FORCE
	@if not exist QTHttpGet\ mkdir QTHttpGet\ & if not exist QTHttpGet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QTHttpGet\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QTHttpGet\QTHttpGet.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-QTHttpGet-uninstall_subtargets: FORCE
	@if not exist QTHttpGet\ mkdir QTHttpGet\ & if not exist QTHttpGet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QTHttpGet\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QTHttpGet\QTHttpGet.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-QtYahooFinanceLib-qmake_all: sub-QTHttpGet-qmake_all FORCE
	@if not exist QtYahooFinanceLib\ mkdir QtYahooFinanceLib\ & if not exist QtYahooFinanceLib\ exit 1
	cd QtYahooFinanceLib\ && $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtYahooFinanceLib\QtYahooFinanceLib.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtYahooFinanceLib\ && $(MAKE) -f Makefile qmake_all
sub-QtYahooFinanceLib: sub-QTHttpGet FORCE
	@if not exist QtYahooFinanceLib\ mkdir QtYahooFinanceLib\ & if not exist QtYahooFinanceLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtYahooFinanceLib\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtYahooFinanceLib\QtYahooFinanceLib.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-QtYahooFinanceLib-make_first: sub-QTHttpGet-make_first FORCE
	@if not exist QtYahooFinanceLib\ mkdir QtYahooFinanceLib\ & if not exist QtYahooFinanceLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtYahooFinanceLib\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtYahooFinanceLib\QtYahooFinanceLib.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-QtYahooFinanceLib-all: sub-QTHttpGet-all FORCE
	@if not exist QtYahooFinanceLib\ mkdir QtYahooFinanceLib\ & if not exist QtYahooFinanceLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtYahooFinanceLib\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtYahooFinanceLib\QtYahooFinanceLib.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-QtYahooFinanceLib-clean: sub-QTHttpGet-clean FORCE
	@if not exist QtYahooFinanceLib\ mkdir QtYahooFinanceLib\ & if not exist QtYahooFinanceLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtYahooFinanceLib\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtYahooFinanceLib\QtYahooFinanceLib.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-QtYahooFinanceLib-distclean: sub-QTHttpGet-distclean FORCE
	@if not exist QtYahooFinanceLib\ mkdir QtYahooFinanceLib\ & if not exist QtYahooFinanceLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtYahooFinanceLib\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtYahooFinanceLib\QtYahooFinanceLib.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-QtYahooFinanceLib-install_subtargets: sub-QTHttpGet-install_subtargets FORCE
	@if not exist QtYahooFinanceLib\ mkdir QtYahooFinanceLib\ & if not exist QtYahooFinanceLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtYahooFinanceLib\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtYahooFinanceLib\QtYahooFinanceLib.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-QtYahooFinanceLib-uninstall_subtargets: sub-QTHttpGet-uninstall_subtargets FORCE
	@if not exist QtYahooFinanceLib\ mkdir QtYahooFinanceLib\ & if not exist QtYahooFinanceLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtYahooFinanceLib\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtYahooFinanceLib\QtYahooFinanceLib.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-MiscHelpers-qmake_all:  FORCE
	@if not exist MiscHelpers\ mkdir MiscHelpers\ & if not exist MiscHelpers\ exit 1
	cd MiscHelpers\ && $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\MiscHelpers\MiscHelpers.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MiscHelpers\ && $(MAKE) -f Makefile qmake_all
sub-MiscHelpers: FORCE
	@if not exist MiscHelpers\ mkdir MiscHelpers\ & if not exist MiscHelpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MiscHelpers\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\MiscHelpers\MiscHelpers.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-MiscHelpers-make_first: FORCE
	@if not exist MiscHelpers\ mkdir MiscHelpers\ & if not exist MiscHelpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MiscHelpers\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\MiscHelpers\MiscHelpers.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-MiscHelpers-all: FORCE
	@if not exist MiscHelpers\ mkdir MiscHelpers\ & if not exist MiscHelpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MiscHelpers\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\MiscHelpers\MiscHelpers.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-MiscHelpers-clean: FORCE
	@if not exist MiscHelpers\ mkdir MiscHelpers\ & if not exist MiscHelpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MiscHelpers\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\MiscHelpers\MiscHelpers.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-MiscHelpers-distclean: FORCE
	@if not exist MiscHelpers\ mkdir MiscHelpers\ & if not exist MiscHelpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MiscHelpers\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\MiscHelpers\MiscHelpers.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-MiscHelpers-install_subtargets: FORCE
	@if not exist MiscHelpers\ mkdir MiscHelpers\ & if not exist MiscHelpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MiscHelpers\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\MiscHelpers\MiscHelpers.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-MiscHelpers-uninstall_subtargets: FORCE
	@if not exist MiscHelpers\ mkdir MiscHelpers\ & if not exist MiscHelpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MiscHelpers\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\MiscHelpers\MiscHelpers.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-qhttpserver-qmake_all:  FORCE
	@if not exist qhttpserver\ mkdir qhttpserver\ & if not exist qhttpserver\ exit 1
	cd qhttpserver\ && $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\qhttpserver\qhttpserver.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qhttpserver\ && $(MAKE) -f Makefile qmake_all
sub-qhttpserver: FORCE
	@if not exist qhttpserver\ mkdir qhttpserver\ & if not exist qhttpserver\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qhttpserver\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\qhttpserver\qhttpserver.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-qhttpserver-make_first: FORCE
	@if not exist qhttpserver\ mkdir qhttpserver\ & if not exist qhttpserver\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qhttpserver\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\qhttpserver\qhttpserver.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-qhttpserver-all: FORCE
	@if not exist qhttpserver\ mkdir qhttpserver\ & if not exist qhttpserver\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qhttpserver\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\qhttpserver\qhttpserver.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-qhttpserver-clean: FORCE
	@if not exist qhttpserver\ mkdir qhttpserver\ & if not exist qhttpserver\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qhttpserver\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\qhttpserver\qhttpserver.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-qhttpserver-distclean: FORCE
	@if not exist qhttpserver\ mkdir qhttpserver\ & if not exist qhttpserver\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qhttpserver\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\qhttpserver\qhttpserver.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-qhttpserver-install_subtargets: FORCE
	@if not exist qhttpserver\ mkdir qhttpserver\ & if not exist qhttpserver\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qhttpserver\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\qhttpserver\qhttpserver.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-qhttpserver-uninstall_subtargets: FORCE
	@if not exist qhttpserver\ mkdir qhttpserver\ & if not exist qhttpserver\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qhttpserver\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\qhttpserver\qhttpserver.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-QtWebServiceApi-qmake_all: sub-qhttpserver-qmake_all FORCE
	@if not exist QtWebServiceApi\ mkdir QtWebServiceApi\ & if not exist QtWebServiceApi\ exit 1
	cd QtWebServiceApi\ && $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtWebServiceApi\QtWebServiceApi.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtWebServiceApi\ && $(MAKE) -f Makefile qmake_all
sub-QtWebServiceApi: sub-qhttpserver FORCE
	@if not exist QtWebServiceApi\ mkdir QtWebServiceApi\ & if not exist QtWebServiceApi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtWebServiceApi\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtWebServiceApi\QtWebServiceApi.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-QtWebServiceApi-make_first: sub-qhttpserver-make_first FORCE
	@if not exist QtWebServiceApi\ mkdir QtWebServiceApi\ & if not exist QtWebServiceApi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtWebServiceApi\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtWebServiceApi\QtWebServiceApi.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-QtWebServiceApi-all: sub-qhttpserver-all FORCE
	@if not exist QtWebServiceApi\ mkdir QtWebServiceApi\ & if not exist QtWebServiceApi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtWebServiceApi\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtWebServiceApi\QtWebServiceApi.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-QtWebServiceApi-clean: sub-qhttpserver-clean FORCE
	@if not exist QtWebServiceApi\ mkdir QtWebServiceApi\ & if not exist QtWebServiceApi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtWebServiceApi\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtWebServiceApi\QtWebServiceApi.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-QtWebServiceApi-distclean: sub-qhttpserver-distclean FORCE
	@if not exist QtWebServiceApi\ mkdir QtWebServiceApi\ & if not exist QtWebServiceApi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtWebServiceApi\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtWebServiceApi\QtWebServiceApi.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-QtWebServiceApi-install_subtargets: sub-qhttpserver-install_subtargets FORCE
	@if not exist QtWebServiceApi\ mkdir QtWebServiceApi\ & if not exist QtWebServiceApi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtWebServiceApi\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtWebServiceApi\QtWebServiceApi.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-QtWebServiceApi-uninstall_subtargets: sub-qhttpserver-uninstall_subtargets FORCE
	@if not exist QtWebServiceApi\ mkdir QtWebServiceApi\ & if not exist QtWebServiceApi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtWebServiceApi\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtWebServiceApi\QtWebServiceApi.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: CPPStockBackend.pro C:\Qt\5.6\msvc2015_64\mkspecs\win32-msvc2015\qmake.conf C:\Qt\5.6\msvc2015_64\mkspecs\features\spec_pre.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\common\angle.conf \
		C:\Qt\5.6\msvc2015_64\mkspecs\common\msvc-base.conf \
		C:\Qt\5.6\msvc2015_64\mkspecs\common\msvc-desktop.conf \
		C:\Qt\5.6\msvc2015_64\mkspecs\qconfig.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_clucene_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_labscontrols_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_labstemplates_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_platformsupport_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_script.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_script_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webengine.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webengine_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginecore.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\qt_functions.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\qt_config.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\win32\qt_config.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\win32-msvc2015\qmake.conf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\spec_post.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\exclusive_builds.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\default_pre.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\win32\default_pre.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\resolve_config.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\default_post.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\qml_debug.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\win32\rtti.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\precompile_header.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\warn_on.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\win32\windows.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\testcase_targets.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\exceptions.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\yacc.prf \
		C:\Qt\5.6\msvc2015_64\mkspecs\features\lex.prf \
		CPPStockBackend.pro
	$(QMAKE) -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile CPPStockBackend.pro
C:\Qt\5.6\msvc2015_64\mkspecs\features\spec_pre.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\common\angle.conf:
C:\Qt\5.6\msvc2015_64\mkspecs\common\msvc-base.conf:
C:\Qt\5.6\msvc2015_64\mkspecs\common\msvc-desktop.conf:
C:\Qt\5.6\msvc2015_64\mkspecs\qconfig.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_core.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_help.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_labscontrols_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_labstemplates_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_location.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_network.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_script.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialbus.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webengine.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webengine_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginecore.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\5.6\msvc2015_64\mkspecs\features\qt_functions.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\qt_config.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\win32\qt_config.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\win32-msvc2015\qmake.conf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\spec_post.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\exclusive_builds.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\default_pre.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\win32\default_pre.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\resolve_config.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\default_post.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\qml_debug.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\win32\rtti.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\precompile_header.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\warn_on.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\win32\windows.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\testcase_targets.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\exceptions.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\yacc.prf:
C:\Qt\5.6\msvc2015_64\mkspecs\features\lex.prf:
CPPStockBackend.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile CPPStockBackend.pro

qmake_all: sub-BackEndApplication-qmake_all sub-JsonWriter-qmake_all sub-QTHttpGet-qmake_all sub-QtYahooFinanceLib-qmake_all sub-MiscHelpers-qmake_all sub-qhttpserver-qmake_all sub-QtWebServiceApi-qmake_all FORCE

make_first: sub-BackEndApplication-make_first sub-JsonWriter-make_first sub-QTHttpGet-make_first sub-QtYahooFinanceLib-make_first sub-MiscHelpers-make_first sub-qhttpserver-make_first sub-QtWebServiceApi-make_first  FORCE
all: sub-BackEndApplication-all sub-JsonWriter-all sub-QTHttpGet-all sub-QtYahooFinanceLib-all sub-MiscHelpers-all sub-qhttpserver-all sub-QtWebServiceApi-all  FORCE
clean: sub-BackEndApplication-clean sub-JsonWriter-clean sub-QTHttpGet-clean sub-QtYahooFinanceLib-clean sub-MiscHelpers-clean sub-qhttpserver-clean sub-QtWebServiceApi-clean  FORCE
distclean: sub-BackEndApplication-distclean sub-JsonWriter-distclean sub-QTHttpGet-distclean sub-QtYahooFinanceLib-distclean sub-MiscHelpers-distclean sub-qhttpserver-distclean sub-QtWebServiceApi-distclean  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-BackEndApplication-install_subtargets sub-JsonWriter-install_subtargets sub-QTHttpGet-install_subtargets sub-QtYahooFinanceLib-install_subtargets sub-MiscHelpers-install_subtargets sub-qhttpserver-install_subtargets sub-QtWebServiceApi-install_subtargets FORCE
uninstall_subtargets: sub-BackEndApplication-uninstall_subtargets sub-JsonWriter-uninstall_subtargets sub-QTHttpGet-uninstall_subtargets sub-QtYahooFinanceLib-uninstall_subtargets sub-MiscHelpers-uninstall_subtargets sub-qhttpserver-uninstall_subtargets sub-QtWebServiceApi-uninstall_subtargets FORCE

sub-BackEndApplication-debug: sub-QtYahooFinanceLib-debug sub-QtWebServiceApi-debug
	@if not exist BackEndApplication\ mkdir BackEndApplication\ & if not exist BackEndApplication\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BackEndApplication\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\BackEndApplication\BackEndApplication.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-JsonWriter-debug:
	@if not exist JsonWriter\ mkdir JsonWriter\ & if not exist JsonWriter\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd JsonWriter\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\JsonWriter\JsonWriter.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-QTHttpGet-debug:
	@if not exist QTHttpGet\ mkdir QTHttpGet\ & if not exist QTHttpGet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QTHttpGet\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QTHttpGet\QTHttpGet.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-QtYahooFinanceLib-debug: sub-QTHttpGet-debug
	@if not exist QtYahooFinanceLib\ mkdir QtYahooFinanceLib\ & if not exist QtYahooFinanceLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtYahooFinanceLib\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtYahooFinanceLib\QtYahooFinanceLib.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-MiscHelpers-debug:
	@if not exist MiscHelpers\ mkdir MiscHelpers\ & if not exist MiscHelpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MiscHelpers\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\MiscHelpers\MiscHelpers.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-qhttpserver-debug:
	@if not exist qhttpserver\ mkdir qhttpserver\ & if not exist qhttpserver\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qhttpserver\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\qhttpserver\qhttpserver.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-QtWebServiceApi-debug: sub-qhttpserver-debug
	@if not exist QtWebServiceApi\ mkdir QtWebServiceApi\ & if not exist QtWebServiceApi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtWebServiceApi\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtWebServiceApi\QtWebServiceApi.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-BackEndApplication-debug sub-JsonWriter-debug sub-QTHttpGet-debug sub-QtYahooFinanceLib-debug sub-MiscHelpers-debug sub-qhttpserver-debug sub-QtWebServiceApi-debug

sub-BackEndApplication-release: sub-QtYahooFinanceLib-release sub-QtWebServiceApi-release
	@if not exist BackEndApplication\ mkdir BackEndApplication\ & if not exist BackEndApplication\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BackEndApplication\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\BackEndApplication\BackEndApplication.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-JsonWriter-release:
	@if not exist JsonWriter\ mkdir JsonWriter\ & if not exist JsonWriter\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd JsonWriter\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\JsonWriter\JsonWriter.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-QTHttpGet-release:
	@if not exist QTHttpGet\ mkdir QTHttpGet\ & if not exist QTHttpGet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QTHttpGet\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QTHttpGet\QTHttpGet.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-QtYahooFinanceLib-release: sub-QTHttpGet-release
	@if not exist QtYahooFinanceLib\ mkdir QtYahooFinanceLib\ & if not exist QtYahooFinanceLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtYahooFinanceLib\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtYahooFinanceLib\QtYahooFinanceLib.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-MiscHelpers-release:
	@if not exist MiscHelpers\ mkdir MiscHelpers\ & if not exist MiscHelpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MiscHelpers\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\MiscHelpers\MiscHelpers.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-qhttpserver-release:
	@if not exist qhttpserver\ mkdir qhttpserver\ & if not exist qhttpserver\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qhttpserver\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\qhttpserver\qhttpserver.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-QtWebServiceApi-release: sub-qhttpserver-release
	@if not exist QtWebServiceApi\ mkdir QtWebServiceApi\ & if not exist QtWebServiceApi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtWebServiceApi\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtWebServiceApi\QtWebServiceApi.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
release: sub-BackEndApplication-release sub-JsonWriter-release sub-QTHttpGet-release sub-QtYahooFinanceLib-release sub-MiscHelpers-release sub-qhttpserver-release sub-QtWebServiceApi-release

sub-BackEndApplication-check: sub-QtYahooFinanceLib-check sub-QtWebServiceApi-check
	@if not exist BackEndApplication\ mkdir BackEndApplication\ & if not exist BackEndApplication\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BackEndApplication\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\BackEndApplication\BackEndApplication.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-JsonWriter-check:
	@if not exist JsonWriter\ mkdir JsonWriter\ & if not exist JsonWriter\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd JsonWriter\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\JsonWriter\JsonWriter.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-QTHttpGet-check:
	@if not exist QTHttpGet\ mkdir QTHttpGet\ & if not exist QTHttpGet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QTHttpGet\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QTHttpGet\QTHttpGet.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-QtYahooFinanceLib-check: sub-QTHttpGet-check
	@if not exist QtYahooFinanceLib\ mkdir QtYahooFinanceLib\ & if not exist QtYahooFinanceLib\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtYahooFinanceLib\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtYahooFinanceLib\QtYahooFinanceLib.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-MiscHelpers-check:
	@if not exist MiscHelpers\ mkdir MiscHelpers\ & if not exist MiscHelpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MiscHelpers\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\MiscHelpers\MiscHelpers.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-qhttpserver-check:
	@if not exist qhttpserver\ mkdir qhttpserver\ & if not exist qhttpserver\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qhttpserver\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\qhttpserver\qhttpserver.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-QtWebServiceApi-check: sub-qhttpserver-check
	@if not exist QtWebServiceApi\ mkdir QtWebServiceApi\ & if not exist QtWebServiceApi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd QtWebServiceApi\ && ( if not exist Makefile $(QMAKE) "C:\Users\Chris Glynn Pelech\Documents\QTProjects\CPPStockBackend\QtWebServiceApi\QtWebServiceApi.pro" -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
check: sub-BackEndApplication-check sub-JsonWriter-check sub-QTHttpGet-check sub-QtYahooFinanceLib-check sub-MiscHelpers-check sub-qhttpserver-check sub-QtWebServiceApi-check
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

